//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the igvc_waypoint_nav package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __igvc_waypoint_nav__WAYPOINTNAVDYNCFGCONFIG_H__
#define __igvc_waypoint_nav__WAYPOINTNAVDYNCFGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace igvc_waypoint_nav
{
  class WaypointNavDynCfgConfigStatics;

  class WaypointNavDynCfgConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(WaypointNavDynCfgConfig &config, const WaypointNavDynCfgConfig &max, const WaypointNavDynCfgConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const WaypointNavDynCfgConfig &config1, const WaypointNavDynCfgConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, WaypointNavDynCfgConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const WaypointNavDynCfgConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, WaypointNavDynCfgConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const WaypointNavDynCfgConfig &config) const = 0;
      virtual void getValue(const WaypointNavDynCfgConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T WaypointNavDynCfgConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T WaypointNavDynCfgConfig::* field;

      virtual void clamp(WaypointNavDynCfgConfig &config, const WaypointNavDynCfgConfig &max, const WaypointNavDynCfgConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const WaypointNavDynCfgConfig &config1, const WaypointNavDynCfgConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, WaypointNavDynCfgConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const WaypointNavDynCfgConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, WaypointNavDynCfgConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const WaypointNavDynCfgConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const WaypointNavDynCfgConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, WaypointNavDynCfgConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, WaypointNavDynCfgConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<WaypointNavDynCfgConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(WaypointNavDynCfgConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("enable"==(*_i)->name){enable = boost::any_cast<bool>(val);}
        if("gain"==(*_i)->name){gain = boost::any_cast<double>(val);}
        if("speed"==(*_i)->name){speed = boost::any_cast<double>(val);}
        if("frame_skip"==(*_i)->name){frame_skip = boost::any_cast<int>(val);}
        if("hue_low"==(*_i)->name){hue_low = boost::any_cast<int>(val);}
        if("hue_high"==(*_i)->name){hue_high = boost::any_cast<int>(val);}
        if("sat_low"==(*_i)->name){sat_low = boost::any_cast<int>(val);}
        if("sat_high"==(*_i)->name){sat_high = boost::any_cast<int>(val);}
        if("val_low"==(*_i)->name){val_low = boost::any_cast<int>(val);}
        if("val_high"==(*_i)->name){val_high = boost::any_cast<int>(val);}
        if("cont_area"==(*_i)->name){cont_area = boost::any_cast<int>(val);}
        if("mask_top"==(*_i)->name){mask_top = boost::any_cast<double>(val);}
        if("mask_right"==(*_i)->name){mask_right = boost::any_cast<double>(val);}
        if("targ_line"==(*_i)->name){targ_line = boost::any_cast<double>(val);}
        if("test_length"==(*_i)->name){test_length = boost::any_cast<double>(val);}
        if("test_time"==(*_i)->name){test_time = boost::any_cast<double>(val);}
        if("track_width"==(*_i)->name){track_width = boost::any_cast<double>(val);}
        if("wheel_radius"==(*_i)->name){wheel_radius = boost::any_cast<double>(val);}
      }
    }

    bool enable;
double gain;
double speed;
int frame_skip;
int hue_low;
int hue_high;
int sat_low;
int sat_high;
int val_low;
int val_high;
int cont_area;
double mask_top;
double mask_right;
double targ_line;
double test_length;
double test_time;
double track_width;
double wheel_radius;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool enable;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gain;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double speed;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int frame_skip;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hue_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int hue_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int sat_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int sat_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int val_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int val_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cont_area;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mask_top;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mask_right;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double targ_line;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double test_length;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double test_time;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double track_width;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_radius;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("WaypointNavDynCfgConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const WaypointNavDynCfgConfig &__max__ = __getMax__();
      const WaypointNavDynCfgConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const WaypointNavDynCfgConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const WaypointNavDynCfgConfig &__getDefault__();
    static const WaypointNavDynCfgConfig &__getMax__();
    static const WaypointNavDynCfgConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const WaypointNavDynCfgConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void WaypointNavDynCfgConfig::ParamDescription<std::string>::clamp(WaypointNavDynCfgConfig &config, const WaypointNavDynCfgConfig &max, const WaypointNavDynCfgConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class WaypointNavDynCfgConfigStatics
  {
    friend class WaypointNavDynCfgConfig;

    WaypointNavDynCfgConfigStatics()
    {
WaypointNavDynCfgConfig::GroupDescription<WaypointNavDynCfgConfig::DEFAULT, WaypointNavDynCfgConfig> Default("Default", "", 0, 0, true, &WaypointNavDynCfgConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enable = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enable = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enable = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<bool>("enable", "bool", 0, "Enable", "", &WaypointNavDynCfgConfig::enable)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<bool>("enable", "bool", 0, "Enable", "", &WaypointNavDynCfgConfig::enable)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gain = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gain = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gain = 1.7;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("gain", "double", 0, "Gain", "", &WaypointNavDynCfgConfig::gain)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("gain", "double", 0, "Gain", "", &WaypointNavDynCfgConfig::gain)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.speed = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.speed = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.speed = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("speed", "double", 0, "Speed", "", &WaypointNavDynCfgConfig::speed)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("speed", "double", 0, "Speed", "", &WaypointNavDynCfgConfig::speed)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frame_skip = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frame_skip = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frame_skip = 4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("frame_skip", "int", 0, "Frame Skip", "", &WaypointNavDynCfgConfig::frame_skip)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("frame_skip", "int", 0, "Frame Skip", "", &WaypointNavDynCfgConfig::frame_skip)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hue_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hue_low = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hue_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("hue_low", "int", 0, "Hue Low", "", &WaypointNavDynCfgConfig::hue_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("hue_low", "int", 0, "Hue Low", "", &WaypointNavDynCfgConfig::hue_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hue_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hue_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hue_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("hue_high", "int", 0, "Hue High", "", &WaypointNavDynCfgConfig::hue_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("hue_high", "int", 0, "Hue High", "", &WaypointNavDynCfgConfig::hue_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sat_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sat_low = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sat_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("sat_low", "int", 0, "Sat Low", "", &WaypointNavDynCfgConfig::sat_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("sat_low", "int", 0, "Sat Low", "", &WaypointNavDynCfgConfig::sat_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sat_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sat_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sat_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("sat_high", "int", 0, "Sat High", "", &WaypointNavDynCfgConfig::sat_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("sat_high", "int", 0, "Sat High", "", &WaypointNavDynCfgConfig::sat_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.val_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.val_low = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.val_low = 144;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("val_low", "int", 0, "Value Low", "", &WaypointNavDynCfgConfig::val_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("val_low", "int", 0, "Value Low", "", &WaypointNavDynCfgConfig::val_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.val_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.val_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.val_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("val_high", "int", 0, "Value High", "", &WaypointNavDynCfgConfig::val_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("val_high", "int", 0, "Value High", "", &WaypointNavDynCfgConfig::val_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cont_area = 1000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cont_area = 5000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cont_area = 1000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("cont_area", "int", 0, "Contour Area", "", &WaypointNavDynCfgConfig::cont_area)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<int>("cont_area", "int", 0, "Contour Area", "", &WaypointNavDynCfgConfig::cont_area)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mask_top = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mask_top = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mask_top = 3.4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("mask_top", "double", 0, "Mask Top", "", &WaypointNavDynCfgConfig::mask_top)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("mask_top", "double", 0, "Mask Top", "", &WaypointNavDynCfgConfig::mask_top)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mask_right = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mask_right = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mask_right = 2.28;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("mask_right", "double", 0, "Mask Right", "", &WaypointNavDynCfgConfig::mask_right)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("mask_right", "double", 0, "Mask Right", "", &WaypointNavDynCfgConfig::mask_right)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.targ_line = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.targ_line = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.targ_line = 5.13;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("targ_line", "double", 0, "Target Line", "", &WaypointNavDynCfgConfig::targ_line)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("targ_line", "double", 0, "Target Line", "", &WaypointNavDynCfgConfig::targ_line)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.test_length = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.test_length = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.test_length = 2.245;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("test_length", "double", 0, "Test Length", "", &WaypointNavDynCfgConfig::test_length)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("test_length", "double", 0, "Test Length", "", &WaypointNavDynCfgConfig::test_length)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.test_time = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.test_time = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.test_time = 17.424;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("test_time", "double", 0, "Test Time", "", &WaypointNavDynCfgConfig::test_time)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("test_time", "double", 0, "Test Time", "", &WaypointNavDynCfgConfig::test_time)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.track_width = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.track_width = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.track_width = 0.35;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("track_width", "double", 0, "Track Width", "", &WaypointNavDynCfgConfig::track_width)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("track_width", "double", 0, "Track Width", "", &WaypointNavDynCfgConfig::track_width)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_radius = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_radius = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_radius = 0.035595;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("wheel_radius", "double", 0, "Wheel Radius", "", &WaypointNavDynCfgConfig::wheel_radius)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr(new WaypointNavDynCfgConfig::ParamDescription<double>("wheel_radius", "double", 0, "Wheel Radius", "", &WaypointNavDynCfgConfig::wheel_radius)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(WaypointNavDynCfgConfig::AbstractGroupDescriptionConstPtr(new WaypointNavDynCfgConfig::GroupDescription<WaypointNavDynCfgConfig::DEFAULT, WaypointNavDynCfgConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<WaypointNavDynCfgConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<WaypointNavDynCfgConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    WaypointNavDynCfgConfig __max__;
    WaypointNavDynCfgConfig __min__;
    WaypointNavDynCfgConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const WaypointNavDynCfgConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static WaypointNavDynCfgConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &WaypointNavDynCfgConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const WaypointNavDynCfgConfig &WaypointNavDynCfgConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const WaypointNavDynCfgConfig &WaypointNavDynCfgConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const WaypointNavDynCfgConfig &WaypointNavDynCfgConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<WaypointNavDynCfgConfig::AbstractParamDescriptionConstPtr> &WaypointNavDynCfgConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<WaypointNavDynCfgConfig::AbstractGroupDescriptionConstPtr> &WaypointNavDynCfgConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const WaypointNavDynCfgConfigStatics *WaypointNavDynCfgConfig::__get_statics__()
  {
    const static WaypointNavDynCfgConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = WaypointNavDynCfgConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __WAYPOINTNAVDYNCFGRECONFIGURATOR_H__
